config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  root 'static#index'

  get "company" => "static#company"
  get "more_info" => "static#more_info"

  namespace :admin do
    root "hotels#index"

    resources :bookings, only: [:index, :show, :update]

    resources :hotels do
      resources :rooms do
        resources :room_availabilities,  path: :avalability
      end
    end
  end

  resources :bookings, only: [:index, :show, :create, :update]

  get "rooms" => "rooms#index", path: :s, as: :s
  get "rooms/:room_id/:availability_id" => "rooms#show", as: :room

  get "booking/:id" => "bookings#show", as: :show_booking
  post "booking/:id" => "bookings#update", as: :cancel_booking
  post "book/:availability_id" => "bookings#create", as: :book_room
  get "bookings" => "bookings#index", as: :user_bookings

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :room_availabilities, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :hotel
  mount_uploader :image, ImageUploader
  mount_uploader :img_extra1, ImageUploader
  mount_uploader :img_extra2, ImageUploader
  validate :image_size
  validates_presence_of :name, :description, :image

  hstore_accessor :extra_info,
    internet: :boolean,
    tv: :boolean,
    sofa: :boolean,
    air: :boolean,
    breakfast: :boolean


  private

    def image_size
      if image.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < AdminController
  before_action :set_hotel
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = @hotel.rooms
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    @room = @hotel.rooms.new(room_params)
    if @room.save
      redirect_to admin_hotel_rooms_path, notice: "Room created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(room_params)
      redirect_to admin_hotel_rooms_path, notice: "Room edited"
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to admin_hotel_rooms_path, notice: 'Room was successfully destroyed.'
  end

  private

    def set_room
      @room = Room.find(params[:id])
    end

    def set_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end


    def room_params
      params.require(:room).permit(:name, :image, :rating, :img_extra1, :img_extra2, :description, extra_info: [:internet, :tv, :closet, :sofa, :air, :breakfast] )
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index

    if params[:location].present? && params[:arrival].present?
      @search_date = DateTime.civil(*params[:arrival].sort.map(&:last).map(&:to_i))
      @available_rooms_near = RoomAvailability.availables(@search_date).rooms_near_to(params[:location], 20)
      @available_hotels = []
    elsif params[:location].present?
      @search_date = DateTime.now
      @available_rooms_near = RoomAvailability.availables(@search_date).rooms_near_to(params[:location], 20)
      @available_hotels = []
    elsif params[:arrival].present?
      @search_date = DateTime.civil(*params[:arrival].sort.map(&:last).map(&:to_i))
      @available_rooms_near = RoomAvailability.availables(@search_date).rooms_near_to([request.location.latitude, request.location.longitude], 20)
      #@available_rooms_near = RoomAvailability.availables(@search_date).rooms_near_to(params[:location], 20)
      @available_hotels = []
    end

  end

  def show
    #@room = Room.find(params[:room_id])
    @room_availability = RoomAvailability.includes(:room).find(params[:availability_id])
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/rooms/_availability.html.erb
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#<%= "room-av-#{availability.id}" %>" aria-expanded="false" aria-controls="<%= "room-av-#{availability.id}" %>" class="collapsed">
          <%= availability.start.to_formatted_s(:short) %>  <span class="pull-right"><%= "#{availability.hours} hours" %> | <%= availability.available?? "Available" : "Not available" %> | <%= "$#{availability.price}" %></span>
        </a>
      </h4>
    </div>
    <div id="<%= "room-av-#{availability.id}" %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">

        <%= form_for [:admin, @hotel, @room, availability], html: {class: "form-inline"} do |f| %>

          <div class="form-group">
            <%= f.label :start, "Start Date/Time Availability" %><br />
            <%= f.datetime_select :start, { ampm: true }, { class: "form-control" } %>
          </div>
          <div class="form-group">
            <%= f.label :available %><br />
            <%= f.select :available, [["Available", 1], ["Not available", 0]], {}, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :hours %><br />
            <%= f.select :hours, RoomAvailability::HOURS, {}, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :price %><br />
            <%= f.number_field :price, class: "form-control" %>
          </div>

          <div class="text-center"><br />
            <%= f.submit "Update", class: "btn btn-primary form-control" %>
            <%= link_to "Delete", admin_hotel_room_room_availability_path(@hotel, @room, availability), method: :delete, class: "btn btn-danger" %>
          </div>




        <% end %>




      </div>
    </div>
  </div

app/views/admin/rooms/_form.html.erb
<%= form_for [:admin, @hotel, @room], html: {multipart: true} do |f| %>
  <% if @room.errors.full_messages.any? %>
    <div class="errors">
      <h3>There's some errors on the form:</h3>
      <ul>
      <% @room.errors.full_messages.each do |error_message| %>
        <li><%= error_message %> <br /></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.bootsy_area :description, class: "form-control", rows: "10" %>
  </div>

  <div class="form-group">
    <%= f.label :rating %><br />
    <%= f.select :rating, options_for_select((1..5).step(1).to_a.map{|s| ["#{s} stars", s]}), class: "form-control", rows: "10" %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Main image" %><br>
    <%= image_tag @room.try(:image).url, { class: "img-rounded", width: "100%" } %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :img_extra1, "Extra image 1" %><br>
    <%= image_tag @room.try(:img_extra1).url, { class: "img-rounded", width: "100%" } %>
    <%= f.file_field :img_extra1, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :img_extra2, "Extra image 2" %><br>
    <%= image_tag @room.try(:img_extra2).url, { class: "img-rounded", width: "100%" } %>
    <%= f.file_field :img_extra2, class: "form-control" %>
  </div>

  <h4>This room includes</h4>
  <div class="row form-group">

    <%= f.fields_for :extra_info, OpenStruct.new(f.object.extra_info) do |e| %>

      <div class="col-md-6 text-center">

        <%= e.label :internet %>
        <%= e.check_box :internet  %> <br>


        <%= e.label :tv %>
        <%= e.check_box :tv %>  <br>

        <%= e.label :sofa %>
        <%= e.check_box :sofa %>  <br>
      </div>

      <div class="col-md-6 text-center">
        <%= e.label :breakfast %>
        <%= e.check_box :breakfast %>  <br>

        <%= e.label :air %>
        <%= e.check_box :air %>  <br>
      </div>

    <% end %>

  </div>
  <div class="row">
    <p class="text-center"><%= f.submit "Submit", class: "btn btn-primary" %>  <%= link_to 'Back to rooms', admin_hotel_rooms_path, class: "btn btn-default" %></p>
  </div>
<% end %>

app/views/admin/rooms/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Editing Room</h1>
  <%= render 'form' %>
</div>

app/views/admin/rooms/index.html.erb
<div class="container">
  <h3>Rooms for <%=  @hotel.name %></h3>

  <% @rooms.each do |room| %>

    <div class="col-md-3 admin-room-preview">
      <div class="image">
        <%= image_tag room.image.url, width: "100%" if room.image? %>
      </div>
      <div class="description">
        <h4><%= link_to room.name, admin_hotel_room_path(@hotel, room), { "data-toggle" => "tooltip", "data-placement" => "bottom", "title" => "Click to manage availabilities" } %>
          <span class="stars pull-right">
            <% room.rating.times do %>
              <i class="fa fa-star"></i>
            <% end %>
          </span>
        </h4>
        <p class="text-right text-muted">Availables: <%=  room.room_availabilities.availables(DateTime.now).count %></p>
        <p class="text-center"> <%= link_to "Edit Room", edit_admin_hotel_room_path(@hotel, room), class: "btn btn-primary" %>
            <%= link_to 'Destroy', admin_hotel_room_path(@hotel, room), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </p>
      </div>
    </div>

  <% end %>

  <div class="col-md-3 admin-new-room">

    <div class="description">
      <h4><%= link_to "New room", new_admin_hotel_room_path %></h4>
    </div>
  </div>


</div>

app/views/admin/rooms/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New Room</h1>
  <%= render 'form' %>
</div>

app/views/admin/rooms/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <div class="row">
          <div class="col-md-12"><h3><%= @room.name %></h3></div>
        </div>
      </div>
      <div class="panel-heading">
        <%= @room.description.html_safe %>
      </div>
      <div class="panel-body">
        <h4>Current availabilities for this room:</h4>
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <% @room.room_availabilities.each do |availability| %>
            <%= render partial: "availability", locals: { availability: availability} %>
            <br>
          <% end %>
        </div>
      </div>
      <div class="panel-footer text-center">
        <%= link_to 'Back', admin_hotel_rooms_path, class: "btn btn-default" %>
        <%= link_to 'Add Availability', new_admin_hotel_room_room_availability_path(@hotel, @room), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>