config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  root 'static#index'

  get "company" => "static#company"
  get "more_info" => "static#more_info"

  namespace :admin do
    root "hotels#index"

    resources :bookings, only: [:index, :show, :update]

    resources :hotels do
      resources :rooms do
        resources :room_availabilities,  path: :avalability
      end
    end
  end

  resources :bookings, only: [:index, :show, :create, :update]

  get "rooms" => "rooms#index", path: :s, as: :s
  get "rooms/:room_id/:availability_id" => "rooms#show", as: :room

  get "booking/:id" => "bookings#show", as: :show_booking
  post "booking/:id" => "bookings#update", as: :cancel_booking
  post "book/:availability_id" => "bookings#create", as: :book_room
  get "bookings" => "bookings#index", as: :user_bookings

end

app/views/shared/_footer.html.erb
<div class="container home-footer">
  <div class="row footer">
    <div class="col-md-10 col-md-offset-1 text-center">
      <div class="row text-left">
        <div class="col-md-4 col-md-offset-4">
          <h4>Company</h4>
          <ul class="list-unstyled">
            <li><a href="/company#mission">Mission</a></li>
            <li><a href="/company#values">Our values</a></li>
            <li><a href="/company#team">Team</a></li>
            <li><a href="/company#jobs">Jobs</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h4>More about GetNapp</h4>
          <ul class="list-unstyled">
            <li><a href="/more_info#security">Trust and security</a></li>
            <li><a href="/more_info#sitemap">Site map</a></li>
            <li><a href="/more_info#apps">Mobile apps</a></li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="col-md-12">
        <h4>Follow us:</h4>
        <ul class="list-inline social-media">
          <li><i class="fa fa-facebook fa-3x"></i></li>
          <li><i class="fa fa-twitter fa-3x"></i></li>
          <li><i class="fa fa-instagram fa-3x"></i></li>
          <li><i class="fa fa-linkedin fa-3x"></i></li>
          <li><i class="fa fa-pinterest fa-3x"></i></li>
        </ul>
        <p>&copy; GetNapp, Inc</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to ("Get<strong>Napp</strong> - Hotel admin").html_safe, root_path, class: "navbar-brand"  %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <%= form_tag s_path, class: "navbar-form", method: :get do %>
            <div class="form-group">
              <%= text_field_tag :location, params[:location], class: "form-control", id: "location-input", placeholder: "Location" %>
            </div>
            <%= submit_tag "Search", name: nil, class: "btn btn-danger" %>
          <% end %>
<!--
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->


        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">GetNapp <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/company#mission">Mission</a></li>
              <li><a href="/company#values">Values</a></li>
            </ul>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/shared/_navbar_user.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to ("Get<strong>Napp</strong>").html_safe, root_path, class: "navbar-brand"  %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <%= form_tag s_path, class: "navbar-form", method: :get do %>
            <div class="form-group">
              <%= text_field_tag :location, params[:location], class: "form-control", id: "location-input", placeholder: "Location" %>
            </div>
            <%= submit_tag "Search", name: nil, class: "btn btn-danger" %>
          <% end %>
<!--
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->

        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= "#{current_user.name} #{current_user.last_name}" %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "My account", edit_user_registration_path %></li>
              <li><%= link_to "My bookings", user_bookings_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
  </div>
</nav>