config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  root 'static#index'

  get "company" => "static#company"
  get "more_info" => "static#more_info"

  namespace :admin do
    root "hotels#index"

    resources :bookings, only: [:index, :show, :update]

    resources :hotels do
      resources :rooms do
        resources :room_availabilities,  path: :avalability
      end
    end
  end

  resources :bookings, only: [:index, :show, :create, :update]

  get "rooms" => "rooms#index", path: :s, as: :s
  get "rooms/:room_id/:availability_id" => "rooms#show", as: :room

  get "booking/:id" => "bookings#show", as: :show_booking
  post "booking/:id" => "bookings#update", as: :cancel_booking
  post "book/:availability_id" => "bookings#create", as: :book_room
  get "bookings" => "bookings#index", as: :user_bookings

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :user
  has_many :rooms, dependent: :destroy
  has_many :room_availabilities, through: :rooms, dependent: :destroy
  has_many :bookings, through: :rooms, dependent: :destroy
  reverse_geocoded_by :latitude, :longitude
  mount_uploader :image, ImageUploader
  validate :image_size
  validates_presence_of :name, :image, :address, :description, :latitude, :longitude

  private

    def image_size
      if image.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < AdminController

  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  def index
    @hotels = current_user.hotels
  end

  def show
  end

  def new
    @hotel = Hotel.new
  end

  def edit
  end

  def create
    @hotel = current_user.hotels.new(hotel_params)
    if @hotel.save
      redirect_to admin_hotels_path, notice: "Hotel created"
    else
      render :new
    end
  end

  def update
    if @hotel.update(hotel_params)
      redirect_to admin_hotels_path, notice: "Hotel edited"
    else
      render :edit
    end
  end

  def destroy
    @hotel.destroy
    redirect_to admin_hotels_path, notice: 'Hotel was successfully destroyed.'
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:name, :image, :address, :description, :latitude, :longitude)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @search = params[:q]
  end

  def show
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/hotels/_form.html.erb
<%= form_for [:admin, @hotel], html: { multipart: true } do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.bootsy_area :description, class: "form-control", rows: 10 %>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :latitude %><br>
      <%= f.text_field :latitude, class: "form-control", id: "input-latitude" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :longitude %><br>
      <%= f.text_field :longitude, class: "form-control", id: "input-longitude" %>
    </div>
    <div class="col-md-12">
      <div id="map-canvas"></div>
    </div>
  </div>

  <br>

  <div class="form-group actions text-center">
    <%= f.submit "Save Hotel", class: "btn btn-primary" %>
  </div>
<% end %>




<script>
  var map = new google.maps.Map(document.getElementById('map-canvas'), {
      zoom: 15,
      center: new google.maps.LatLng(6.2067854,-75.5703812),
      mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  var myMarker = new google.maps.Marker({
      position: new google.maps.LatLng(6.2067854,-75.5703812),
      draggable: true
  });

  google.maps.event.addListener(myMarker, 'dragend', function(evt){
      document.getElementById('input-latitude').value = evt.latLng.lat().toFixed(3);
      document.getElementById('input-longitude').value = evt.latLng.lng().toFixed(3);
  });

  google.maps.event.addListener(myMarker, 'dragstart', function(evt){
      document.getElementById('current').innerHTML = '<p>Currently dragging marker...</p>';
  });

  map.setCenter(myMarker.position);
  myMarker.setMap(map);
</script>

app/views/admin/hotels/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Editing Hotel</h1>
  <%= render 'form' %>
</div>

app/views/admin/hotels/index.html.erb
<div class="container">


  <div class="col-md-10 col-md-offset-1">



  <h1>Current Hotels</h1>
  <% @hotels.each do |hotel| %>

    <div class="col-md-12 hotel-preview">
      <div class="col-md-5 hotel-preview-img"><%= image_tag hotel.image.url, width: "100%" if hotel.image? %></div>
      <div class="col-md-7 hotel-preview-data">
        <h3><%= link_to hotel.name, admin_hotel_path(hotel) %></h3>
        <p class="text-muted"><%= hotel.address %></p>

        <p class="text-center"><%= link_to 'See Rooms', admin_hotel_rooms_path(hotel), class: "btn btn-success" %>
          <%= link_to 'Edit', edit_admin_hotel_path(hotel), class: "btn btn-primary" %>
          <%= link_to 'Destroy', admin_hotel_path(hotel), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
      </div>
    </div>
  <% end %>

  <p class="text-center"><%= link_to 'New Hotel', new_admin_hotel_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/admin/hotels/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New Hotel</h1>
  <%= render 'form' %>
</div>

app/views/admin/hotels/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <div class="row">
          <div class="col-md-12"><h3><%= @hotel.name %></h3></div>
        </div>
      </div>
      <div class="panel-heading">
        <%= @hotel.description.html_safe %>
      </div>
      <div class="panel-body">
        <p><strong>Address:</strong> <%= @hotel.address %></p>
        <p><strong>Coords:</strong>  Longitude: <%= @hotel.longitude %> | Latitude: <%= @hotel.latitude %></p>
      </div>
      <div class="panel-footer text-center">
        <%= link_to 'Back', admin_hotels_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>