config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  root 'static#index'

  get "company" => "static#company"
  get "more_info" => "static#more_info"

  namespace :admin do
    root "hotels#index"

    resources :bookings, only: [:index, :show, :update]

    resources :hotels do
      resources :rooms do
        resources :room_availabilities,  path: :avalability
      end
    end
  end

  resources :bookings, only: [:index, :show, :create, :update]

  get "rooms" => "rooms#index", path: :s, as: :s
  get "rooms/:room_id/:availability_id" => "rooms#show", as: :room

  get "booking/:id" => "bookings#show", as: :show_booking
  post "booking/:id" => "bookings#update", as: :cancel_booking
  post "book/:availability_id" => "bookings#create", as: :book_room
  get "bookings" => "bookings#index", as: :user_bookings

end

app/views/admin/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to ("Get<strong>Napp</strong> - Hotel admin").html_safe, admin_root_path, class: "navbar-brand"  %>
        <!-- <a class="navbar-brand" href="#">Get<strong>Napp</strong> - Hotel admin</a> -->
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to ("<span class='glyphicon glyphicon-home' aria-hidden='true'></span> Hotels").html_safe, admin_hotels_path %></li>
          <li><%= link_to ("<span class='glyphicon glyphicon-calendar' aria-hidden='true'></span> Bookings").html_safe, admin_bookings_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mixer Gutierrez <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "My account", edit_user_registration_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
  </div>
</nav>